### PR TITLE
Misc issues

### PR DESCRIPTION
**Pull request by vl-ti**
Incorrect line number was configured for integer overflow test.
Adjusted README

### CODE REVIEW

**Comment by vl-ti** [comment]
Sorry, which file? Could you please elaborate?

**Comment by rocky** [comment]
all.yaml

**Comment by vl-ti** [comment]
Hm in frames of PR https://github.com/EthereumAnalysisBenchmarks/Omnibus/pull/1, benchconf/Omnibus.yaml has been renamed to benchconf/all.yaml

**Comment by rocky** [comment]
Sorry I meant PR #2

**Comment by vl-ti** [comment]
Ah, I was looking into PR https://github.com/EthereumAnalysisBenchmarks/Omnibus/pull/2 as well, and didn't noticed that all.yaml has been removed as PR has been created before PR #1 got merged into master.

Ok, now I see that each test case got its own config. The thing is that I am working on a task to integrate Omnibus with one of the analysers. In order to implement it, Omnibus must be fixed. I see two options here:
  * Merge my fix into current master. But it will require to modify integration logic later on, as PR #2 changes project structure
  * Resolve merge conflicts and merge PR #2 into master. I can try to help you on this task

**Comment by rocky** [comment]
@thec00n is the lead here.

**Pull request merged**
